theme: jekyll-theme-slate

title: [Residente del mal xd]
description: [A short description of your site's purpose]

show_downloads: true

github:
  Descarga(exe): https://github.com/pages-themes/modernist
